[package]
name = "caesar"
version = "0.6.0"
authors = ["abyss"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
